### PR TITLE
use cdn for latest and update templates

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by dgershman** [comment]
CDN is really meant for those who have no ability to import the npm package.  Can you fully use that and add NPM here?

**Review by dgershman — CHANGES_REQUESTED** [review]
use npm

**Comment by pjaudiomv** [comment]
yea I used the cdn so we wouldn't have to update and the ketchups would always have the latest

**Comment by dgershman** [comment]
You’d have to manually update other things like themes.  We can automate the update potentially of Ketchup based off NPM package version changes if need be.

**Review by dgershman — APPROVED** [review]

**Pull request merged**
